### PR TITLE
Reshape project to use rebar3

### PR DESCRIPTION
**Pull request by davisp**
This reshapes the repository so that it matches a standard OTP layout which lets us use rebar to compile everything. This fixes the undefined references for the NIF API which were causing your segfault.

### CODE REVIEW

**Comment by jcoglan** [comment]
@davisp Thank you so much for helping with this :) Forgive me, I'm quite new to Erlang -- how do I run and compile my examples now? I tried the `compile` command but it doesn't know about the paths and files needed to pull in `jq.h`.

**Comment by jcoglan** [comment]
I also notice `enc` is a binary -- what does it do and where does it come from?

**Comment by janl** [comment]
> how do I run and compile my examples now?

I don’t think rebar supports just building random C stuff, so non-if C code would still be done in your `Makefile`

> but it doesn't know about the paths and files needed to pull in jq.h.

for the nif: see https://github.com/davisp/jiffy/blob/master/rebar.config for examples of how to specify compiler options.

> I also notice enc is a binary

Long story: rebar2 long ago included a mechanism for building C code. rebar3 has removed that code and moved into a plugin that doesn’t seem to work as reliably. So Paul created `enc` from the sources of rebar2 that handles the C compilation parts and uses it inside rebar3.

**Comment by jcoglan** [comment]
We got it working :) thanks again @davisp!

**Comment by davisp** [comment]
Looks like @janl covered it and was exactly right. For the curious, `enc` is built from this repo:

https://github.com/davisp/erlang-native-compiler

There's also a rebar3 port compiler plugin but it had problems for jiffy when it was a dependency of a dependency, hence this approach.

**Comment by davisp** [comment]
Also, no worries. If you need any help or want me to review anything just give me a ping on Slack or Twitter and I'd be more than happy to help.

**Pull request merged**
